### ISSUE TITLE
Top-level `this` is the same as `global`, not `exports`

### ISSUE THREAD

**Issue by eventualbuddha** [esnext/esnext#87]
The CommonJS plugin is incorrectly treating `this.x = 1;` as equivalent to `exports.x = 1;`, which isn't true. We should consider changing top-level `this` to `global`.

**Comment by btd** [comment]
You seems not right there:
```
$ echo 'console.log(exports === this)' >> test.js
$ node test.js
true
```

**Comment by eventualbuddha** [comment]
Your are correct. Thanks!
