### ISSUE TITLE
Thanks from Knex.

### ISSUE THREAD

**Issue by rhys-vdw** [esnext/esnext#93]
Hey sorry to pollute your issues, but I just wanted to give a big thank you to @eventualbuddha for `esnext`'s role in [this diff](https://github.com/tgriesser/knex/pull/1416/files).

It sucked, but it sucked a lot less due to `esnext`, so thanks!

**Comment by eventualbuddha** [comment]
No worries about polluting the issues 😊 I'm always happy to hear someone found it useful. Best of luck with merging, and if you encountered any issues or have suggestions for improvement please feel free to report them in new issues.
