### ISSUE TITLE
playground don't works

### ISSUE THREAD

**Issue by yukulele** [esnext/esnext#94]
es6 playground don't works: https://esnext.github.io/esnext

error show: `esnext.convert is not a function`

**Comment by madskonradsen** [comment]
It seems to work, guess this can be closed @yukulele ? :)

**Comment by alangpierce** [comment]
While it seems to not crash, the output in the example suggests that it's not running all of the transformations, so that would be good to fix. It gives:

```js
import { memoize } from 'lodash';

var upperCase = memoize(function(string) {
  return string.toUpperCase();
});
```

But I'd expect something like this:

```js
import { memoize } from 'lodash';

let upperCase = memoize(string => string.toUpperCase());
```

**Comment by yukulele** [comment]
@madskonradsen it works on chrome but not on firefox for me.
